version: '3.8'
#

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production 
    volumes:
      - .:/app
    command: ["/server"]  

